spring:
  application:
    name: spring-cloud-config-server

  cloud:
    function:
      definition: consumer
    stream:
      output-bindings: producer
      bindings:
        consumer-in-0:
          destination: my-topic
          group: consumer
          content-type: application/json
          binder: kafka
        producer:
          destination: my-topic
          content-type: application/json
          binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            security:
              protocol: PLAINTEXT





